language: python
python:
  - "3.6"
matrix:
  include:
    - env: TOXENV=py27
    - env: TOXENV=py36
install:
- pip install pipenv
script:
- pipenv install --dev --skip-lock
- pipenv run pipenv check
- pipenv run pylint laniakea
- pipenv run tox
branches:
  only:
  - master
deploy:
  provider: pypi
  user: mozillasecurity
  password:
    secure: wYc7AFbw8u0mN0DznvZxOiulZ0Tm1TPAReUni4evVMpaYyv6AcL6yglSoGfF+0qiUMgJxY9JJGTBnhXs5GUZSbH9dZylTHQmkA+IOcyph+iUsJ263l3eAuGYhdxCeLjNXzQGQK6mS20MqVwThZgn5eHUixhgKrHGZIHCjaCMwpI=
  on:
    tags: true
notifications:
  slack:
    secure: duNeJwuDMG1ZVi26dipUzullK+Dd6nsBIq4d+72KWKD2R7qjyZP4bFBFRFzkSHVqohl/meD3EYPXZICy6RoDWaxPQcBK9oL6KZAlEnsyueRWhunsMDAyOuhyAaRD1FhL717eeyB0dygU0iaTDujpOghDfRY99C9KeWXkzmqD0ss=
