language: python
python:
- '3.6'
matrix:
  include:
  - env: TOXENV=py27
  - env: TOXENV=py36
install:
- pip install pipenv
script:
- pipenv install --dev --skip-lock
- pipenv run pipenv check
- pipenv run pylint laniakea
- pipenv run tox
branches:
  only:
  - master
deploy:
  provider: pypi
  user: mozillasecurity
  password:
    secure: mdBZiiCszOYuliQQVeyW60aJbXNcRQ4A09SXR1GgYQcdZSMEvGPc/FffuVwkOtczhEGy9zQ62hCgxIRKf7NILew/VU/67RiEN8zXMU41nFhaW0oFBRyE4Bc8d/9WXub2B4HKZb5LUZWhn+dTJF30IEnRwfRSB7PTnqz9UhGhiSg=
  distributions: sdist bdist_wheel
  on:
    tags: true
notifications:
  slack:
    secure: duNeJwuDMG1ZVi26dipUzullK+Dd6nsBIq4d+72KWKD2R7qjyZP4bFBFRFzkSHVqohl/meD3EYPXZICy6RoDWaxPQcBK9oL6KZAlEnsyueRWhunsMDAyOuhyAaRD1FhL717eeyB0dygU0iaTDujpOghDfRY99C9KeWXkzmqD0ss=
