language: python
python:
- '3.6'
matrix:
  include:
  - env: TOXENV=py36
before_install:
- pip install pipenv
script:
- pipenv install --dev
- pipenv run tox
deploy:
  provider: pypi
  user: mozillasecurity
  password:
    secure: "RFde7fS5I/akSew25GWGcd9G/sq6z8twknYIgud3Cxwc+Da+Sq8X3GuA8S26wAHeG/ktgrLP7YQi5bJeiWc6NpFeEulTkKUcFTQhoNdrdGbJp/HpOct/Smdu2CkNAmzBnhJDBMGFZ/MZVLlw7KLm6yAWqJGfk54YfvgpkqenuKY="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branches:
      only:
      - master
  skip_cleanup: true
notifications:
  slack:
    secure: duNeJwuDMG1ZVi26dipUzullK+Dd6nsBIq4d+72KWKD2R7qjyZP4bFBFRFzkSHVqohl/meD3EYPXZICy6RoDWaxPQcBK9oL6KZAlEnsyueRWhunsMDAyOuhyAaRD1FhL717eeyB0dygU0iaTDujpOghDfRY99C9KeWXkzmqD0ss=
